name: Unit Test

on:
  workflow_call:
    inputs:
      node-versions:
        required: false
        type: string
        default: '20,22,24,25'

      typecheck:
        required: false
        type: string
        default: pnpm run typecheck

      lint:
        required: false
        type: string
        default: pnpm run lint

      build:
        required: false
        type: string
        default: pnpm run build

      test:
        required: false
        type: string
        default: pnpm run test

      skip-lint:
        required: false
        type: boolean
        default: false

      skip-test:
        required: false
        type: boolean
        default: false

      build-for-lint:
        required: false
        type: boolean
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip-lint }}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build-for-lint }}

      - name: Type Check
        run: ${{ inputs.typecheck }}
        if: ${{ inputs.typecheck != '' }}

      - name: Lint
        run: ${{ inputs.lint }}
        if: ${{ inputs.lint != '' }}

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ${{ fromJson(format('[{0}]', inputs.node-versions)) }}
      fail-fast: false

    if: ${{ !inputs.skip-test }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: ${{ inputs.build }}

      - name: Unit Test
        run: ${{ inputs.test }}
